const $ = s => document.querySelector(s);
const names = {ads:'Iklan lewat Nemu',collab:'Collab posting',social:'Kelola sosial media'};
let service='ads';
const money=v=>'Rp'+Number(v||0).toLocaleString('id-ID');
const channels=()=>[...document.querySelectorAll('[name=channel]:checked')].map(x=>x.value);
const value=id=>$('#'+id).value.trim();
const label=id=>$('#'+id).selectedOptions?.[0]?.textContent||value(id);
const set=(id,text)=>$('#'+id).textContent=text;
function section(id,show){const el=$('#'+id);el.hidden=!show;el.querySelectorAll('input,select,textarea').forEach(x=>x.disabled=!show)}
function required(id,on){$('#'+id).required=!!on}
function update(){
 const ads=service==='ads',social=service==='social',ch=channels();$('#summary-social-budget-row').hidden=!social;set('summary-social-budget',value('social-budget')?label('social-budget'):'Belum dipilih');$('.panel-heading p').textContent=social?'Ceritakan kebutuhanmu sebagai bahan diskusi Nemu dengan agency.':service==='collab'?'Ceritakan produk dan kesiapan konten untuk collab bersama Nemu.':'Jawab dengan bahasa sehari-hari. Pengaturan iklan dibantu tim Nemu.';
 section('product-section',!social);section('product-purpose',service==='collab');
 section('ads-intake',ads);section('budget-section',ads);section('ad-consent',ads);section('video-section',social);section('social-account-detail',social&&value('social-account-state')==='existing');required('social-accounts',social&&value('social-account-state')==='existing');section('social-volume-detail',social&&value('social-volume')==='known');required('videos',social&&value('social-volume')==='known');required('social-designs',social&&value('social-volume')==='known');
 section('collab-info',service==='collab');const collab=service==='collab',made= value('collab-source')==='nemu';section('collab-create',collab&&made);section('collab-existing',collab&&!made);section('collab-material-detail',collab&&made&&value('collab-material')==='ready');required('collab-material-link',collab&&made&&value('collab-material')==='ready');$('#collab-content-link').placeholder=value('collab-content-type')==='post'?'https://www.instagram.com/p/…':'https://drive.google.com/…';set('collab-link-help',value('collab-content-type')==='post'?'Tempel link posting. Tim memeriksa apakah posting bisa dikolaborasikan atau perlu disiapkan ulang.':'Kirim link file atau folder yang dapat dibuka tim Nemu.');$('.operator').hidden=!ads;
 const destination=value('destination');
 section('destination-detail',ads&&destination!==''&&destination!=='help');required('destination-value',ads&&destination!==''&&destination!=='help');
 const phone=destination==='whatsapp';$('#destination-value').type=phone?'tel':'url';$('#destination-value').pattern=phone?'[+0-9 ()-]{8,20}':'.*';
 set('destination-label',phone?'Nomor WhatsApp toko *':'Link halaman tujuan *');$('#destination-value').placeholder=phone?'Contoh: +62 812 3456 7890':'https://…';
 set('destination-help',phone?'Nomor aktif yang akan membalas pertanyaan calon pembeli.':'Link harus bisa dibuka calon pembeli, bukan link pengelolaan toko.');
 section('location-detail',ads&&value('location')==='custom');required('cities',ads&&value('location')==='custom');
 section('date-detail',ads&&value('timing')==='date');required('start-date',ads&&value('timing')==='date');
 section('asset-detail',ads&&value('asset-status')==='ready');required('asset-link',ads&&value('asset-status')==='ready');
 section('collab-date-detail',collab&&value('collab-timing')==='date');required('collab-date',collab&&value('collab-timing')==='date');
 const stockDetail=ads&&['limited','preorder'].includes(value('ad-stock'));section('ad-stock-detail',stockDetail);required('ad-stock-notes',stockDetail);
 section('ad-promo-detail',ads&&value('ad-promo')==='yes');
 $('#ad-promo-end').setCustomValidity(value('ad-promo')==='yes'&&value('ad-promo-start')&&value('ad-promo-end')&&value('ad-promo-end')<value('ad-promo-start')?'Tanggal berakhir tidak boleh sebelum tanggal mulai.':'');
 set('goal-warning',value('ad-goal')==='sales'?'Untuk mengejar pembelian, tim perlu memastikan transaksi bisa diukur. Link marketplace saja belum memastikan iklan dapat dioptimalkan untuk pembelian.':destination==='whatsapp'?'Jalur ke WhatsApp perlu diperiksa sesuai kanal. Pilihan ini tidak otomatis menjadi iklan pesan di semua platform.':'');
 const days=Number(value('duration'));set('daily-estimate',days?'Perkiraan rata-rata '+money(Number(value('budget'))/days)+' per hari untuk seluruh kanal. Ini pembagian matematika, bukan estimasi hasil atau minimum platform.':'Durasi dan pembagian dana akan diusulkan tim Nemu.');
 set('summary-service',names[service]);set('summary-channel',ch.join(', ')||'Belum dipilih');set('summary-product',value('product')||'Belum dipilih');$('#summary-product').parentElement.hidden=social;
 $('#summary-purpose').previousElementSibling.textContent=social?'Target konten':ads?'Hasil yang dicari':'Jenis produk';
 set('summary-purpose',social?(value('social-volume')==='known'?value('videos')+' video + '+value('social-designs')+' foto/carousel':'Rekomendasi tim'):ads?(value('ad-goal')?label('ad-goal'):'Belum dipilih'):($('[name=purpose]:checked')?.value||'Belum dipilih'));
 set('total',ads?money(value('budget')):service==='collab'?'Belum ditetapkan':'Rp6.000.000/bln');$('#total').style.fontSize=ads?'23px':'18px';set('total-label',ads?'Total dana iklan':social?'Harga mulai':'Biaya layanan');
 set('cost-help',ads?'Untuk semua kanal dan seluruh periode. Alokasi dan minimum platform dicek tim.':service==='collab'?'Belum ada harga tetap. Menunggu kurasi dan konfirmasi.':'Harga per bulan. Jumlah konten dan cakupan kerja dikonfirmasi dalam penawaran final.');
 set('counter',value('notes').length+'/1000');
 document.querySelectorAll('[data-budget]').forEach(b=>b.classList.toggle('chosen',Number(b.dataset.budget)===Number(value('budget'))));
 const missing=[...$('#promotion-form').elements].filter(x=>!x.disabled&&x.willValidate&&!x.validity.valid);
 set('validation',!ch.length?'Pilih minimal satu kanal promosi.':missing.length?'Lengkapi jawaban bertanda * untuk membuat brief.':(social?'Brief awal lengkap untuk diskusi dengan agency.':'Jawaban lengkap untuk review. Tim masih perlu memeriksa kesiapan tayang.'));$('#validation').classList.remove('error');
 if(ads)set('execution-brief',makeBrief());
}
function makeBrief(){
 const ch=channels(),goal=value('ad-goal'),dest=value('destination');
 const lines=['BRIEF PERMINTAAN NEMU — DRAF UNTUK REVIEW','Tidak membuat kampanye. Bukan persetujuan tayang atau pembayaran.','', 'LAYANAN: '+names[service],'KANAL: '+(ch.join(', ')||'Belum dipilih'),'PRODUK: '+(value('product')||'Belum dipilih')];
 if(service!=='ads'){
 if(service==='social')lines.push('TAHAP: Brief awal untuk meeting Nemu dengan agency. Belum menjadi pesanan atau persetujuan harga.','HARGA MULAI: Rp6.000.000 per bulan; harga final mengikuti hasil diskusi dan penawaran.','ANGGARAN BULANAN SELLER: '+(value('social-budget')?label('social-budget'):'Belum dipilih'),'BRAND: '+value('social-brand'),'USAHA: '+value('social-business'),'KONDISI AKUN: '+label('social-account-state'),'AKUN: '+(value('social-account-state')==='existing'?value('social-accounts'):'Perlu dibuat / disiapkan'),'KEBUTUHAN UTAMA: '+label('social-goal'),'LINGKUP DIMINTA: '+([...document.querySelectorAll('[name=\"social-scope\"]:checked')].map(x=>x.value).join(', ')||'Minta rekomendasi'),'TARGET KONTEN: '+(value('social-volume')==='known'?value('videos')+' video + '+value('social-designs')+' foto/carousel; '+label('social-content-period'):'Minta rekomendasi'),'KESIAPAN BAHAN: '+label('social-materials'),'LINK BAHAN / REFERENSI: '+(value('social-reference')||'Belum ada'),'MULAI: '+label('social-start'),'AGENDA MEETING AGENCY: Gunakan kebutuhan, prioritas, kesiapan bahan, dan anggaran seller untuk meminta rekomendasi lingkup, jumlah konten, kebutuhan produksi, jadwal, dan biaya. Detail teknis belum ditetapkan. Kembalikan rekomendasi serta penawaran kepada seller untuk persetujuan.');
 else {lines.push('JENIS PRODUK: '+($('[name=purpose]:checked')?.value||'Belum dipilih'),'SUMBER KONTEN: '+label('collab-source'),'AKUN / BRAND: '+value('collab-handle'),'PESAN UTAMA: '+value('collab-highlight'),'LINK PRODUK: '+value('collab-product-link'),'WAKTU POSTING: '+(value('collab-timing')==='date'?value('collab-date')+' (usulan)':'Fleksibel, mengikuti kesepakatan'));
 if(value('collab-source')==='nemu')lines.push('BAHAN: '+label('collab-material'),'LINK BAHAN: '+(value('collab-material')==='ready'?value('collab-material-link'):'Perlu pengarahan'),'SAMPEL PRODUK: '+label('collab-sample'));
 else lines.push('BENTUK KONTEN: '+label('collab-content-type'),'LINK KONTEN: '+value('collab-content-link'),'IZIN PENYESUAIAN: '+label('collab-edit'),'HAK KONTEN: '+($('#collab-rights').checked?'Dikonfirmasi seller; verifikasi sebelum posting':'Belum dikonfirmasi'));
 lines.push('REVIEW NEMU: Kurasi produk/konten, cek hak materi dan dukungan fitur collab tiap kanal. Sepakati produksi, sampel bila perlu, jadwal, biaya, dan persetujuan materi final. Tidak ada publikasi otomatis.');}
 return lines.concat('CATATAN: '+(value('notes')||'Tidak ada')).join('\n');}

 lines.push('TUJUAN SELLER: '+label('ad-goal'),'ARAHKAN KE: '+label('destination'),'LINK / NOMOR: '+(dest&&dest!=='help'?value('destination-value')||'Belum diisi':'Perlu rekomendasi'),'LOKASI: '+(value('location')==='custom'?value('cities'):label('location')),'CALON PEMBELI: '+(value('buyer')||'Bantu susun dari produk'),'TOTAL BELANJA IKLAN: '+money(value('budget'))+' untuk seluruh kanal','DURASI: '+(value('duration')==='help'?'Perlu rekomendasi':value('duration')+' hari'),'MULAI: '+(value('timing')==='date'?value('start-date')+' (tanggal pilihan; zona waktu operator perlu dikonfirmasi)':'Setelah materi dan penawaran disetujui'),'PEMBAGIAN DANA: Belum ditetapkan; minta persetujuan seller sebelum setup.','PESAN UTAMA: '+(value('selling-point')||'Belum diisi'),'HARGA PRODUK: '+(value('ad-price')?money(value('ad-price')):'Belum diisi'),'STOK: '+label('ad-stock'),'DETAIL STOK: '+(['limited','preorder'].includes(value('ad-stock'))?value('ad-stock-notes'):'Tidak ada detail tambahan'),'PROMO: '+(value('ad-promo')==='yes'?value('ad-promo-terms')+'; '+value('ad-promo-start')+' s.d. '+value('ad-promo-end'):'Tidak ada promo khusus'),'KONFIRMASI DATA PRODUK: '+($('#ad-product-confirm').checked?'Dikonfirmasi seller':'Belum dikonfirmasi'),'MATERI: '+label('asset-status'),'LINK MATERI: '+(value('asset-status')==='ready'?value('asset-link')||'Belum diisi':'Butuh bantuan produksi; biaya belum disepakati'),'CATATAN: '+(value('notes')||'Tidak ada'),'HAK MATERI: '+($('#rights').checked?'Seller menyatakan memiliki hak atau akan mengurus izin; verifikasi sebelum tayang.':'Belum dikonfirmasi'),'', 'ARAH SETUP OPERATOR — WAJIB DIVERIFIKASI');
 if(ch.includes('Instagram')||ch.includes('Facebook'))lines.push('', 'META / '+ch.filter(x=>['Instagram','Facebook'].includes(x)).join(' + '),'Rancangan objective: '+({awareness:'Awareness',messages:'Review Engagement / Leads dan lokasi konversi pesan sesuai akun dan tujuan; pastikan WhatsApp terhubung bila dipakai',views:'Review objective/performance goal yang mendukung video views',traffic:'Traffic; evaluasi optimasi landing page views bila pengukuran tersedia',clicks:'Traffic; evaluasi optimasi link clicks',sales:'Sales bila event pembelian terukur dan akses tersedia; jangan otomatis ganti ke Traffic',help:'Tentukan setelah konsultasi'}[goal]||'Belum dipilih'),'Identitas: akun Instagram / Facebook Nemu (tetap).','Gunakan Page/IG Nemu. Periksa izin penggunaan materi seller; tidak meminta akses akun seller. WhatsApp perlu nomor serta jalur pesan yang kompatibel. Batasi penempatan sesuai kanal yang disepakati; perlu persetujuan untuk perluasan.');
 if(ch.includes('TikTok'))lines.push('', 'TIKTOK ADS','Rancangan objective: '+({awareness:'Reach',messages:'Periksa dukungan Messaging / Lead Generation dan destination pada akun; jangan menganggap link WhatsApp sebagai optimasi pesan',views:'Video Views',traffic:'Traffic; evaluasi landing page view bila tersedia pada akun dan destination',clicks:'Traffic; evaluasi optimasi clicks',sales:'Sales sesuai destination dan pengukuran yang tersedia; akses Shop / event website diperiksa operator',help:'Tentukan setelah konsultasi'}[goal]||'Belum dipilih'),'Materi: gunakan bahan seller atau siapkan penawaran produksi. Tim Nemu menentukan posting baru / Spark, serta mengurus otorisasi internal.','Periksa minimum anggaran campaign/ad group di akun aktif serta mata uang; total usulan tidak otomatis memenuhi minimum.');
 if(ch.includes('YouTube Shorts'))lines.push('', 'GOOGLE ADS / YOUTUBE SHORTS','Rancangan: '+({awareness:'Video Reach atau jenis kampanye pendukung Shorts sesuai akses akun',messages:'Tidak dipetakan otomatis ke iklan pesan. Review jalur destination dan pengukuran; sepakati hasil yang bisa dioptimalkan',views:'Video Views dengan konfigurasi format Shorts yang sesuai',traffic:'Evaluasi kampanye pendukung Shorts untuk kunjungan halaman; verifikasi pengukuran landing page. Jangan menyamakan klik dengan kunjungan',clicks:'Evaluasi kampanye pendukung Shorts dengan tujuan klik; cek pilihan bidding/optimasi yang tersedia di akun',sales:'Evaluasi Demand Gen / kampanye konversi yang mendukung Shorts setelah tracking tervalidasi',help:'Tentukan setelah konsultasi'}[goal]||'Belum dipilih'),'Identitas: channel YouTube Nemu (tetap).','Video: tim Nemu memeriksa bahan dan menyiapkan unggahan pada channel Nemu; produksi baru perlu penawaran.','Pastikan video public/unlisted. Utamakan video vertikal. Siapkan CTA, headline, deskripsi sesuai jenis kampanye. Periksa kontrol format/placement; jangan janjikan Shorts-only tanpa cek konfigurasi.');
 lines.push('', 'SEBELUM TAYANG','- Verifikasi link/nomor, lokasi pengiriman, harga, stok, promo, serta kelayakan produk.','- Tentukan alokasi dana per platform, budget harian/total, tanggal akhir, dan zona waktu. Pisahkan pajak/jasa/produksi dalam penawaran.','- Jika mengejar penjualan: verifikasi akses data dan event pembelian (Meta Pixel/CAPI, TikTok Pixel/Events API, Google conversion tracking atau integrasi Shop sesuai tujuan). Marketplace tanpa akses event belum siap untuk optimasi pembelian.','- Verifikasi format, musik/hak konten, izin iklan, dan masa berlakunya. Semua identitas iklan memakai akun Nemu. Tidak meminta akses atau password akun seller.','- Tentukan bidding, optimization event, targeting, exclusions, CTA, copy, dan URL tracking sesuai akun; ini tugas operator.','- Kirim pratinjau materi dan penawaran ke seller untuk persetujuan. Jangan jalankan dari brief ini saja.');
 return lines.join('\n');
}
function selectService(v){if(!Object.hasOwn(names,v))throw Error('Layanan tidak valid');service=v;document.querySelectorAll('[data-service]').forEach(b=>{let yes=b.dataset.service===v;b.classList.toggle('selected',yes);b.setAttribute('aria-pressed',String(yes));b.querySelector('.choice').textContent=yes?'✓':''});set('notes-label',v==='ads'?'Ada pesan tambahan?':v==='collab'?'Ide untuk posting bersama':'Catatan untuk tim Nemu');$('#notes').placeholder=v==='ads'?'Contoh: Jangan gunakan kata termurah. Stok warna hitam terbatas.':v==='collab'?'Contoh: Video styling kaos baru, tonjolkan warna dan bahan.':'Contoh: Gaya bahasa santai. Ada peluncuran koleksi baru bulan depan.';set('notes-help','Boleh dikosongkan jika tidak ada tambahan.');update()}
$('#promotion-form').noValidate=true;
$('#start-date').min=new Date().toLocaleDateString('en-CA');$('#collab-date').min=$('#start-date').min;
document.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>selectService(b.dataset.service));
document.querySelectorAll('[data-budget]').forEach(b=>b.onclick=()=>{$('#budget').value=b.dataset.budget;update()});
$('#product-search').oninput=()=>{const q=value('product-search').toLowerCase();let matches=0;[...$('#product').options].slice(1).forEach(o=>{o.hidden=!o.textContent.toLowerCase().includes(q);if(!o.hidden)matches++});$('#product').options[0].textContent=matches?'Pilih produk dari tokomu':'Produk tidak ditemukan'};
$('#promotion-form').addEventListener('input',update);$('#promotion-form').addEventListener('change',update);
$('#promotion-form').onsubmit=e=>{e.preventDefault();update();if(!channels().length){set('validation','Pilih minimal satu kanal promosi.');$('#validation').classList.add('error');$('[name=channel]').focus();return}const bad=[...$('#promotion-form').elements].find(el=>!el.disabled&&el.willValidate&&!el.validity.valid);if(bad){set('validation','Masih ada jawaban yang perlu dilengkapi. Lihat field yang ditandai.');$('#validation').classList.add('error');bad.focus();bad.reportValidity();return}const snapshot=makeBrief();const row=document.createElement('tr');[names[service],channels().join(', '),service==='ads'?money(value('budget')):'Belum ditentukan',new Date().toLocaleDateString('id-ID'),'Simulasi'].forEach((v,i)=>{const cell=document.createElement('td');cell.textContent=v;if(i===0){const small=document.createElement('small');small.textContent=service==='social'?value('social-brand'):value('product');cell.append(small)}if(i===4){const btn=document.createElement('button');btn.className='brief-button';btn.textContent='Lihat brief';btn.onclick=()=>{set('saved-brief',snapshot);$('#brief-dialog').showModal()};cell.append(btn)}row.append(cell)});$('#history-body').prepend(row);while($('#history-body').children.length>50)$('#history-body').lastElementChild.remove();set('history-count',$('#history-body').children.length);set('toast','Brief simulasi dicatat. Buka “Lihat brief” untuk membaca jawaban lengkap.');$('#toast').hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').hidden=true,6000);$('#history').scrollIntoView({behavior:'smooth'})};
$('#close-brief').onclick=()=>$('#brief-dialog').close();
$('#download-brief').onclick=()=>{const url=URL.createObjectURL(new Blob([makeBrief()],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='brief-promosi-nemu.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
selectService('ads');
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'select_promotion_service',description:'Pilih layanan dalam pratinjau; tidak mengirim permintaan atau membuat iklan.',inputSchema:{type:'object',properties:{service:{type:'string',enum:['ads','collab','social']}},required:['service'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){selectService(input.service);return {service,label:names[service]}}})).catch(()=>{})}catch{}}
